spring:
  datasource:
    url: jdbc:mysql://localhost:3307/expense_tracker?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: app_user
    password: app_pass_123

  jpa:
    hibernate:
      # ddl-auto: create   # FIRST RUN ONLY: creates schema
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  jpa.defer-datasource-initialization: true
  sql:
    init:
      # mode: always # FIRST-RUN ONLY: seed data
      mode: never

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
