version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: expense-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: expense_tracker
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: my_password
      TZ: Asia/Kolkata
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=caching_sha2_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d:ro
      # Put schema.sql + data.sql here to auto-run on first DB creation
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p$$MYSQL_ROOT_PASSWORD --silent"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  mysql_data:
